PS E:\Vscode_Code\Python\ExcelToTypescript> & C:/Users/29701/AppData/Local/Programs/Python/Python313/python.exe e:/Vscode_Code/Python/ExcelToTypescript/src/tests/test0.py
时间：2025-04-17 17:53:56,743 - 日志
等级：ERROR - 日志信息：解析 INI 文件 else\参考\物编 ini\table\unit.ini 时出
错: While reading from 'else\\参考\\
物编 ini\\table\\unit.ini' [line 39]:
option 'modelScale' in section 'h004' already exists
Traceback (most recent call last):
File "E:\Vscode_Code\Python\ExcelToTypescript\src\core\ini_parser.py", line 44, in parse_ini
files_read = self.config.read(path, encoding='utf-8-sig')
File "C:\Users\29701\AppData\Local\Programs\Python\Python313\Lib\configparser.py", line 735, in read
self.\_read(fp, filename)
~~~~~~~~~~^^^^^^^^^^^^^^
File "C:\Users\29701\AppData\Local\Programs\Python\Python313\Lib\configparser.py", line 1050, in \_read
ParsingError.\_raise_all(self.\_read_inner(fp, fpname))
~~~~~~~~~~~~~~~~^^^^^^^^^^^^
File "C:\Users\29701\AppData\Local\Programs\Python\Python313\Lib\configparser.py", line 1079, in \_read_inner
self.\_handle_rest(st, line, fpname)
~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
File "C:\Users\29701\AppData\Local\Programs\Python\Python313\Lib\configparser.py", line 1105, in \_handle_rest self.\_handle_header(st, mo.group('header'), fpname) if mo else self.\_handle_option(st, line, fpname)

    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^

File "C:\Users\29701\AppData\Local\Programs\Python\Python313\Lib\configparser.py", line 1144, in \_handle_option
raise DuplicateOptionError(st.sectname, st.optname,
fpname, st.lineno)
configparser.DuplicateOptionError: While reading from 'else\\参考\\物编 ini\\table\\unit.ini' [line 39]: option
'modelScale' in section 'h004' already exists
时间：2025-04-17 17:53:56,763 - 日志
等级：INFO - 日志信息：data:{data}
